### ISSUE TITLE
MVP TODO list

### ISSUE THREAD

**Issue by fmichea** [thags15/LiveSplit.TheoryComparisonGenerator#1]
Front-end:

- [x] Turn input red when time typed cannot be parsed as a TimeSpan
- [x] Document display name as optional
- [x] Allow re-ordering of the theory times

Back-end:

- [x] Link general settings and actual comparisons added to splits
- [x] Implement attaching comparisons to splits
- [x] Implement comparison settings filtering based on current run
- [x] Add all necessary comparisons to splits from comparison settings information
- [x] Handle comparison name change more gracefully

Other:

- [x] Run a few test cases loading splits, changing comparions, ...
- [x] Write basic information in README, make sure to mention this is pre-release
