### ISSUE TITLE
GA Release TODO List

### ISSUE THREAD

**Issue by fmichea** [thags15/LiveSplit.TheoryComparisonGenerator#2]
### Front-end

- [x] Allow setting theory time with millisecond precision
- [ ] Add option to import theory comparisons from other layouts. (file browser select perhaps?)

### Back-end

- [x] Fix issue with automatic PB comparison only working with RealTime timing method
- [x] Fix issue with Theory PB comparison being duplicated in the dropdown if you have multiple layouts with Theory Comparison added

### Other

- [x] Add explanation on what Theory Comparison is for newcomers to the concept
